# Generated by Django 6.0.3 on 2026-03-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='recommended_doctor',
            new_name='doctor_specialization',
        ),
    ]
