# Generated by Django 6.0.3 on 2026-03-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='symptomdisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_links', to='ai_recommendations.disease'),
        ),
        migrations.AlterUniqueTogether(
            name='symptomdisease',
            unique_together={('symptom', 'disease')},
        ),
    ]
