# Generated by Django 6.0.3 on 2026-03-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_disease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
