# Generated by Django 6.0.3 on 2026-04-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctor_bio_doctor_is_verified_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(blank=True, help_text='e.g. MBBS, MD, PhD', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Orthopedist', 'Orthopedist'), ('Gynecologist', 'Gynecologist'), ('Pulmonologist', 'Pulmonologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Endocrinologist', 'Endocrinologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Psychiatrist', 'Psychiatrist'), ('Urologist', 'Urologist'), ('Oncologist', 'Oncologist'), ('ENT Specialist', 'ENT Specialist')], max_length=200),
        ),
    ]
